In [21]:
import pandas as pd
import numpy as np


# from google.colab import drive
# drive.mount('/content/drive')
# data = pd.read_csv('/content/drive/MyDrive/ml_datasets/Bengaluru_House_Data.csv')
# data.head()
data = pd.read_csv("archive/Bengaluru_House_Data.csv")

In [22]:
data.shape

(13320, 9)

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 936.7 KB

In [24]:
for column in data.columns:
  print(data[column].value_counts())
  print('*'*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
27 BHK           1
19 BHK           1
16 BHK           1
43 Bedroom       1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Maa 5a      1
AeisePV     1
SJovest     1
ThhtsV      1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
1020 - 1130      1
2758             1
1133 - 1384      1
774              1
4689             1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
96.80       1
63.93       1
40.14       1
231.00      1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [25]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

**here we start our data selection and filling of nan columns**

In [26]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True) #otherwise just include columns with int and float only

In [27]:
data.describe(include='all')

          location   size total_sqft          bath         price
count        13319  13304      13320  13247.000000  13320.000000
unique        1305     31       2117           NaN           NaN
top     Whitefield  2 BHK       1200           NaN           NaN
freq           540   5199        843           NaN           NaN
mean           NaN    NaN        NaN      2.692610    112.565627
std            NaN    NaN        NaN      1.341458    148.971674
min            NaN    NaN        NaN      1.000000      8.000000
25%            NaN    NaN        NaN      2.000000     50.000000
50%            NaN    NaN        NaN      2.000000     72.000000
75%            NaN    NaN        NaN      3.000000    120.000000
max            NaN    NaN        NaN     40.000000   3600.000000

In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  str
 1   size        13304 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [29]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [30]:
data['location'] = data['location'].fillna('Sarjapur Road')

In [31]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
27 BHK           1
19 BHK           1
16 BHK           1
43 Bedroom       1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [32]:
data['size'] = data['size'].fillna('2 BHK')

In [33]:
data['bath'].value_counts() # since this is a int column can fill NAN with median/mean type

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
14.0       1
27.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [34]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [35]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  str
 1   size        13320 non-null  str
 2   total_sqft  13320 non-null  str
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), str(3)
memory usage: 520.4 KB

In [36]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [37]:
data[data.bhk > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [38]:
data['total_sqft'].unique()

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
 ...
        '3124',        '9200',         '613',         '250',        '2395',
 '1020 - 1130',        '2758', '1133 - 1384',         '774',        '4689']
Length: 2117, dtype: str

In [39]:
def convertRange(x):
  temp = x.split('-')
  if(len(temp) == 2):
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

APPLY is used when we want to give a function as refrence and apply will give whatever we have given as input to that function

In [40]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)

In [41]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

Price per sqft

In [42]:
data['price_per_sqft'] = data['price']*100000 / data['total_sqft']

In [43]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [44]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [45]:
data['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1306, dtype: int64

Rducing way to many diffrent types of location and for all locations with value less than 10 houses are marked as others

In [46]:

data['location'] = data['location'].apply(lambda x: x.strip())
location_count = data['location'].value_counts()
location_count

location
Whitefield                                         541
Sarjapur  Road                                     399
Electronic City                                    304
Kanakpura Road                                     273
Thanisandra                                        237
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1295, dtype: int64

In [47]:
location_count_less_10 = location_count[location_count <= 10]
location_count_less_10

location
Ganga Nagar                                        10
Dairy Circle                                       10
Sadashiva Nagar                                    10
Naganathapura                                      10
Nagappa Reddy Layout                               10
                                                   ..
Pattegarhpalya                                      1
Tilak Nagar                                         1
12th cross srinivas nagar banshankari 3rd stage     1
Havanur extension                                   1
Abshot Layout                                       1
Name: count, Length: 1054, dtype: int64

In [48]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
2nd Phase Judicial Layout      11
Marsur                         11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

here we trimmed 1306 types of location to 242 types

**OUTLIER DETECTION and REMOVAL:-**

to know the outliers we check the data using describe for min, avg and max values of each column

In [49]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

here check total_sqft
min-> 1 sqft,
avg -> 1200,
max-> 52k

so  .:. , we check total_sqft_per_bhk

In [50]:
(data['total_sqft']/data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [51]:
data = data[(data['total_sqft']/data['bhk']) >= 300]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [52]:
data.shape

(12530, 7)

In [53]:
data.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

check the max value of the price_per_sqft **outlier for sure**

In [54]:
def remove_outliers_sqft(df):
  df_output = pd.DataFrame()
  for key,subdf in df.groupby('location'): # groupby give key and and its corresponding dataframe(here all values of flat in that loca.)
    m = np.mean(subdf.price_per_sqft)
    s = np.std(subdf.price_per_sqft)
    # for checking the outliers -> 2*s diffrence is good can accept
    gen_df = subdf[(subdf.price_per_sqft > (m-s)) & (subdf.price_per_sqft <= (m+s))]
    df_output = pd.concat([df_output,gen_df],ignore_index=True)
  return df_output
data = remove_outliers_sqft(data)
data.describe() # check max price_per_sqft now

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

**Rule of thumb: In professional machine learning workflows, $2\sigma$ to $3\sigma$ (or the IQR method: $[Q1 - 1.5\cdot\text{IQR}, Q3 + 1.5\cdot\text{IQR}]$) is the standard practice. $1\sigma$ over-trims genuine data points.**




* $2\sigma$ model will be more realistic and robust:In real estate, prices naturally vary (e.g., floor rise, corner plots, luxury amenities).
* By discarding ~32% of data in every location,$1\sigma$ throws away perfectly valid properties as "outliers."
* A $2\sigma$ model learns from ~95% of realistic market conditions, meaning it will generalize much better to unseen real-world

In [55]:
from numpy._core.defchararray import index
# to REMOVE BHK outliers
def remove_outliers_bhk(df):
  exclude_indices = np.array([])
  for location,location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk,bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] = {
          'mean' : np.mean(bhk_df.price_per_sqft),
          'std' : np.std(bhk_df.price_per_sqft),
          'count' : bhk_df.shape[0]
      }
    for bhk,bhk_df in location_df.groupby('bhk'):
      # for finding outliers in 3BHK need values of 2BHK, if(price of 2 > price_3_bhk) outlier for same location
      stats = bhk_stats.get(bhk-1) # here, bhk_stats[bhk-1] nhi kiya bcoz it gives error if(bhk = 3, and 2 doesn't exist)=>so gives error
                                   # .:. .get() is used(throws a None)
      if stats and stats['count'] > 5:
        exclude_indices = np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values)
  return df.drop(exclude_indices,axis = 'index')

In [56]:
data = remove_outliers_bhk(data)

In [57]:
data.shape

(7361, 7)

In [58]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [59]:
data.drop(columns=['size','price_per_sqft'],inplace = True)

**Cleaned Data**

In [60]:
data

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10292                other      1200.0   2.0   70.0    2
10293                other      1800.0   1.0  200.0    1
10296                other      1353.0   2.0  110.0    2
10297                other       812.0   1.0   26.0    1
10300                other      3600.0   5.0  400.0    4

[7361 rows x 5 columns]

In [61]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

MODEL TRAINING STARTS HERE

In [62]:
X = data.drop(columns=['price'])
y = data['price']

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [64]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state = 0)

In [65]:
print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1473, 4)

In [66]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output = False,drop = 'first'),['location']),remainder='passthrough')
# here sparse = false give good nummpy array of 0s and 1s rather than a sparse matrix
# drop = 'first' so that one less column in that numpy array w/o it is also same no need of it
# remainder = 'passthrough' bcoz only need onehotencoding on location all others are int,float not text or cataegorical

In [67]:
scaler = StandardScaler()

In [68]:
lr = LinearRegression()

In [69]:
pipe = make_pipeline(column_trans,scaler,lr)

In [70]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [71]:
y_pred_lr = pipe.predict(X_test)

In [72]:
r2_score(y_test,y_pred_lr)

0.8233783132019374

 **APPLYING  LASSO**

In [73]:
lasso = Lasso()

In [74]:
pipe = make_pipeline(column_trans,scaler,lasso)

In [75]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [76]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.8098660307488847

**APPLYING RIDGE**

In [77]:
ridge = Ridge()
pipe = make_pipeline(column_trans,scaler,ridge)
pipe.fit(X_train,y_train)
y_pred_ridge = pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.8231505594301165

In [81]:
import pickle


# to save the trained model pipeline
with open('RidgeModel.pkl','wb') as f:
  pickle.dump(pipe,f)


# to save the cleaned dataframe
data.to_csv('Cleaned_data.csv',index = False)

In [80]:
#now rest is deployment and in the vs code